---
- name: Actualizar lista de paquetes
  apt: update_cache=yes
- name: Instalar paquetes necesarios
  apt: pkg={{ item }}
  with_items:
    - apache2
    - php7.0
    - mariadb-server
    - mariadb-client
    - python-mysqldb
    - unzip
    - apache2-utils
    - php7.0-dom
    - php7.0-gd
    - php7.0-xml
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-common
    - php7.0-curl
    - php7.0-zip
    - php7.0-mcrypt
    - php7.0-xml
    - php7.0-cli
    - php7.0-apcu
    - php7.0-intl
    - sendmail
