---
- name: Clonamos el repositorio
  command: git clone https://github.com/FranciscoRomero23/hosting-proyecto /home/usuario/hosting-proyecto
- name: Creamos el virtualenv
  command: virtualenv -p /usr/bin/python3 /home/usuario/bottle
- name: Activamos el virtualenv
  command: source /home/usuario/bottle/bin/activate
- name: Instalamos los requeriments
  command: pip3 install -r /home/usuario/hosting-proyecto/Aplicaciones/panel/requeriments.txt
- name: Desactivamos el virtualenv
  command: deactivate
- name: Crear directorio root
  file:
    path: /var/www/html/panel
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
- name: Copiamos los ficheros de la aplicacion
  command: cp -r /home/usuario/hosting-proyecto/Aplicaciones/panel/* /var/www/html/panel/
- name: Copiamos el virtualhost
  file: >
    src=/home/usuario/hosting-proyecto/Aplicaciones/panel/panel.conf
    dest=/etc/apache2/sites-available/panel.conf
- name: Cambiamos permisos directorio root
  command: chown -R www-data:www-data /var/www/html/panel/
- name: Deshabilitamos el virtualhost por defecto
  command: a2dissite 000-default.conf
- name: Habilitamos el virtualhost nuevo
  command: a2ensite panel.conf
  notify: restart apache
