---
- name: Creamos el virtualenv
  command: virtualenv -p /usr/bin/python3 /home/admin/bottle
- name: Instalamos los requeriments
  pip: requirements=/home/admin/hosting-proyecto/Aplicaciones/panel/requeriments.txt virtualenv=/home/admin/bottle
- name: Crear directorio root
  file:
    path: /var/www/html/panel
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
- name: Copiamos los ficheros de la aplicacion
  synchronize:
    src: /home/admin/hosting-proyecto/Aplicaciones/panel/
    dest: /var/www/html/panel
    recursive: True
- name: Copiamos la web principal
  template: >
    src=web.tpl
    dest=/var/www/html/panel/html/web.tpl
- name: Copiamos el virtualhost
  template: >
    src=virtualenv.conf
    dest=/etc/apache2/sites-available/panel.conf
- name: Cambiamos usuarios directorio root
  command: chown -R www-data:www-data /var/www/html/panel/
- name: Cambiamos permisos directorio root
  command: chmod 755 -R /var/www/html/panel/
- name: Deshabilitamos el virtualhost por defecto
  command: a2dissite 000-default.conf
- name: Habilitamos el virtualhost nuevo
  command: a2ensite panel.conf
  notify: restart apache
