---
- name: Crear directorio root
  file:
    path: /var/www/html/{{ root_directory }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
- name: Copiar el index.html
  copy: >
    src=index.html
    dest=/var/www/html/{{ root_directory }}/index.html
- name: Copiar el virtualhost
  copy: >
    src=virtualhost.conf
    dest=/etc/apache2/sites-available/{{ virtualhost }}.conf
- name: Deshabilitamos el virtualhost por defecto   
  command: a2dissite 000-default.conf
- name: Habilitamos el virtualhost nuevo
  command: a2ensite {{ virtualhost }}.conf
  notify: restart apache
