---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Creación de la base de datos
    mysql_db: name=wordpressdb state=present collation=utf8_general_ci
  - name: Creación del usuario de la base de datos
    mysql_user: name=wordpressuser password=wordpress priv="wordpressdb.*:ALL" host=127.0.0.1
  - name: Descarga de wordpress
    get_url:
      url: http://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz
  - name: Descomprimimos los ficheros
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /tmp
  - name: Copiamos los ficheros
    synchronize:
      src: /tmp/wordpress/
      dest: /var/www/html/fjwordpress
      recursive: True
  - name: Copiar el wp-config.php
    copy: >
      src=files/wordpress/wp-config.php
      dest=/var/www/html/fjwordpress/wp-config.php
      owner: www-data
      group: www-data
      mode: 0775
    notify:
      - restart apache

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

